version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: snipeit_app_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  app:
    image: snipe/snipe-it
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=http://umbrel:8592
      - MYSQL_PORT_3306_TCP_ADDR=snipeit_db_1
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=secret
      - APP_TRUSTED_PROXIES=*
      - APP_KEY='base64:0SBsb2k+BjfdeKFq9+brMx0x6uMCttEXMM6txufG1hg='
    ports:
      - 9099:80
    volumes:
      - ${APP_DATA_DIR}/app:/config

  db:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=snipeitroot
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=secret
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s