version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: snipe-it_app_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  app:
    image: lscr.io/linuxserver/snipe-it:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=http://192.168.2.67:8592
      - MYSQL_PORT_3306_TCP_ADDR=snipe-it_db_1
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=secret
      - APP_TRUSTED_PROXIES=*
    ports:
      - 9099:80
    volumes:
      - ${APP_DATA_DIR}/app:/config

  db:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=secret
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql
    restart: always
