version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: mediagoblin_app_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  app:
    image: vimagick/mediagoblin
    environment:
      - MG_USER=umbrel
      - MG_PASS=${APP_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}:/var/lib/mediagoblin
    restart: unless-stopped
