version: "2.1"

networks:
    umbrel_main_network:
      external:
        name: umbrel_main_network

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: umbrel_wireguard
    networks:
      - umbrel_main_network
    extra_hosts:
      - "dockerhost:172.18.0.1"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - SERVERURL=dentropycloud.info #optional
      - SERVERPORT=51820 #optional
      - PEERS=10 #optional
      #- PEERDNS=10.133.0.5 #optional
      #- INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - ${UMBREL_ROOT}/data/storage/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
