version: "3.4"

services:
  app_proxy:
    environment:
      APP_HOST: monica_app_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  app:
    image: monica:4.0
    privileged: true
    depends_on:
      - db
    environment:
      - APP_KEY=base64:96LMP0ii2u/fuSxAm1+OEJD4gUyO84mOiU+uLoWSyls=
      - DB_HOST=db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=secret
      - APP_TRUSTED_PROXIES=*
    volumes:
      - ${APP_DATA_DIR}/config:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=secret
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql
    restart: always
